# Generated by Django 5.1.1 on 2024-09-11 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2024, 9, 11, 18, 59, 11, 246655))),
            ],
        ),
    ]
